

Import("environment")

libturbo = environment.SharedLibrary("turbo", ["plugin.cpp", "script.cpp", "plugloader.cpp"], LIBS=["mozjs-"])
turbo = environment.Program("turbo", ["engine.cpp"], LIBS=["mozjs-", libturbo])

install_libturbo = environment.Install(environment["OURLIBPATH"], libturbo)

Depends(turbo, install_libturbo)

Return("turbo")
