import os
import sys

Import("environment libturbo")

plugins = []

for f in os.listdir(os.getcwd()):
    if os.path.isdir(f):
        plugins.append([SConscript(dirs=[f], exports=["environment", "libturbo"])])

Return("plugins")
