import os
import sys

Import("environment")

environment.Append(CPPPATH=[os.path.join(os.getcwd(), "include")])

libturbo = SConscript(dirs=["engine"], exports=["environment"])
plugins = SConscript(dirs=["plugins"], exports=["environment", "libturbo"])

environment.Install(environment["PLUGINPATH"], plugins)

Return("libturbo")
